In [94]:
import numpy as np
import random

In [95]:
def sum(a, b):
    if a.shape == b.shape:
        c = np.zeros_like(b)
        for i in range(len(a)):
            for j in range(len(a[0])):
                c[i][j] = a[i][j] + b[i][j]
        return c
    else:
        print("dimensioni incombatibili")
        return 0 

In [102]:
a = np.random.random((3, 4)) * 10
print(a)

b = np.random.random((3, 4)) * 10
print(b)

[[3.96715953 1.20753572 9.18001777 0.78526203]
 [8.10110673 9.15483418 7.62207486 6.56992903]
 [2.4640466  2.56834869 2.63018949 9.68195989]]
[[0.51736087 1.04428911 5.51662035 0.55398567]
 [6.6007304  7.88816455 2.90444647 7.46714028]
 [8.82100513 7.76198484 6.73036411 8.55376376]]


In [103]:
c = sum(a, b)
print(c)

[[ 4.48452039  2.25182483 14.69663812  1.3392477 ]
 [14.70183713 17.04299874 10.52652134 14.0370693 ]
 [11.28505173 10.33033353  9.3605536  18.23572365]]
